manually compiled app crashes like this
idRuntime: FATAL EXCEPTION: main
                                                   Process: net.hanshq.hello, PID: 10911
                                                   Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{net.hanshq.hello/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/net.hanshq.hello-2/lib/arm/libhello.so
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app/net.hanshq.hello-2/lib/arm/libhello.so
                                                       at android.app.NativeActivity.onCreate(NativeActivity.java:182)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
05-31 08:52:30.025 802-29549/system_process W/ActivityManager:   Force finishing activity net.hanshq.hello/android.app.NativeActivity
05-31 08:52:30.029 802-10926/system_process W/DropBoxManagerService: Dropping: data_app_crash (1499 > 0 bytes)